package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/joho/godotenv"
	"log"
	"todo-api/database"
	"todo-api/handlers"
	 _ "todo-api/docs" // docs is generated by Swag CLI
	"github.com/swaggo/fiber-swagger"
)


// @title Todo API
// @version 1.0
// @description This is a sample todo server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:3000
// @BasePath /
// @schemes http
func main() {
	if err := godotenv.Load(); err != nil {
		log.Fatal("Error loading .env file")
	}

	database.InitDB()
	defer database.Pool.Close()

	app := fiber.New()

	// Swagger
    app.Get("/swagger/*", fiberSwagger.WrapHandler)

	app.Post("/tasks", handlers.CreateTask)
	app.Get("/tasks", handlers.GetTasks)
	app.Put("/tasks/:id", handlers.UpdateTask)
	app.Delete("/tasks/:id", handlers.DeleteTask)

	log.Fatal(app.Listen(":3000"))
}