version: '3.8'

services:
  db:
    image: postgres:17
    container_name: testovoe-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: todo  # Добавляем явное указание БД
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - testovoe-network

networks:
  testovoe-network:
    driver: bridge